[database]
addrs= "localhost:27018"
user= "iris"
passwd= "irispassword"
database= "rainbow-server-check"

[server]
write_dir="/Users/user/adr038"
file_prefix="adr38"
chain_id=""
promethous_port=9091
only_support_module=""